version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: frankcoin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/migrations.sql:/migrations/migrations.sql:ro

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/frankcoin}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      WEBAPP_URL: ${WEBAPP_URL}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CUSTODIAL_MNEMONIC: ${CUSTODIAL_MNEMONIC}
      BOT_USERNAME: ${BOT_USERNAME:-frankcoin_bot}
      PORT: 8080
    ports:
      - "8080:8080"

  webapp:
    build: ./webapp
    depends_on:
      - backend
    ports:
      - "8081:80"

volumes:
  db_data:
